@startuml Conception

skinparam defaultfontname Verdana
title Spell GUI interaction model

hide empty members
abstract Spell
{
    - MGO:MeshGUIObject
    + setRenderPosition(position:Vec2f):void
    + setRenderSize(scale:Vec2f):void
    + getNumberOfChargesLeft():int
    + addCharge(numberOfCharges:int):void
    + execute():bool
}
class MeshGUIObject
{
  - position:Vec2f
  - vertexArrayStartIndex:int
  - vertexArrayEndIndex:int
  - IndexArrayStartIndex:int
  - IndexArrayEndIndex:int
}
class DescriptionGUI extends MeshGUIObject
{

}
class logTrapSpell implements Spell
{

}
class Icon
class bloodSpell implements Spell
class SpellsGUI
Entity GUIRenderer
class RuneGame
class RuneKeyboard
GUIRenderer "1"--> "1" SpellsGUI : Setup >
SpellsGUI "1" *- "1..*" Spell : Contains >
SpellsGUI "1" -- "1"  RuneGame
RuneGame "1" o-- "1" RuneKeyboard
Spell *-- "1" MeshGUIObject
MeshGUIObject o-- "1" Icon
@enduml

class Université
class Enseignant{
  prénom: String
  nom: String
  courriel: String
}


Université "1" -- "1..*" Enseignant : Emploie >